services:
  api-aztu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-aztu
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app:z
    ports:
      - "8003:8000"
    env_file:
      - .env
    depends_on:
      - postgres-app  

  postgres-app:
    container_name: postgres-aztu
    image: postgres:15-bullseye
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: olo,om7urffo
      POSTGRES_DB: aztu_db
    ports:
      - "5560:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data

volumes:
  pgdb:
  portainer_data:
